calendar_login_page:
    path:     /login
    defaults: { _controller: CalendarBundle:Login:login }

# Page où entrer le mail lors de l'oubli de mot de passe
calendar_oubli_mdp_page:
    path:     /oubliMdpPage
    defaults: { _controller: CalendarBundle:Login:affichageOubliMdp }

calendar_oubli_mdp:
    path:     /envoiMail
    defaults: { _controller: CalendarBundle:Login:sendMail }

# fonction de changement de mot de passe
calendar_modifier_mdp:
    path:     /oubliMdp
    defaults: { _controller: CalendarBundle:Login:verificationNouveauMdp }

# Page du formulaire de changement de mot de passe
calendar_modifier_mdp_page:
    path:     /changementMdpPage
    defaults: { _controller: CalendarBundle:Login:affichageChangementMdp }
    
# Page du formulaire de création de compte   
calendar_creation_compte_page:
    path:     /creationComptePage
    defaults: { _controller: CalendarBundle:Login:affichageCreationCompte }

# fonction de création de compte
calendar_creation_compte:
    path:     /creationCompte
    defaults: { _controller: CalendarBundle:Login:creationCompte }   

calendar_logout:
    path:     /logout
    defaults: { _controller: CalendarBundle:Login:logout }

#affichage page d'acceuil avec seulement les séances du prof
calendar_home_page:
    path:     /accueil
    defaults: { _controller: CalendarBundle:Index:index }
 
#affichage page d'acceuil avec toutes les séances de la BD
calendar_home_page_filtre:
    path:     /accueilFiltre
    defaults: { _controller: CalendarBundle:Index:filtre }

calendar_ajout_matiere:
    path:     /ajoutMatiere
    defaults: { _controller: CalendarBundle:Index:ajoutMatiere }

calendar_ajout_enseignement:
    path:     /ajoutEnseignement
    defaults: { _controller: CalendarBundle:Index:ajoutEnseignement }

calendar_ajout_seance:
    path:     /ajoutSeance
    defaults: { _controller: CalendarBundle:Index:ajoutSeance }

calendar_supprimer_seance:
    path:     /supprimerSeance
    defaults: { _controller: CalendarBundle:Index:supprimerSeance }
    
calendar_gestion_compte:
    path:     /gestionCompte
    defaults: { _controller: CalendarBundle:Compte:compte }

calendar_gestion_compte_maj_email:
    path:     /majEmail
    defaults: { _controller: CalendarBundle:Compte:majEmail }
    
