calendar_login_page:
    path:     /login
    defaults: { _controller: CalendarBundle:Login:login }

calendar_logout:
    path:     /logout
    defaults: { _controller: CalendarBundle:Login:logout }

calendar_home_page:
    path:     /accueil
    defaults: { _controller: CalendarBundle:Index:index }

calendar_ajout_matiere:
    path:     /ajoutMatiere
    defaults: { _controller: CalendarBundle:Index:ajoutMatiere }